#!/bin/bash

factorial(){
	local fact=1
	local num=$1

	for(( i=1;i<=num;i++))
        do 
        fact=$((fact*i))
	done
	echo "the factorial of $num is: $fact"
}
read -p "enter the number : " num
factorial "$num"
